// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:gastos_personales/features/budgets/data/models/budget_model.dart';
import 'package:gastos_personales/features/categories/data/models/category_model.dart';
import 'package:gastos_personales/features/notifications/data/models/notification_model.dart';
import 'package:gastos_personales/features/transactions/data/models/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
